config/routes.rb
Rails.application.routes.draw do
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  root to: 'home#show', via: :get
  resource :dashboard, only: [:show]
  get 'favoursforothers' => 'favoursforothers#show'
  get 'favoursforme' => 'favoursforme#show'
  
  resources :clans, only: [:index, :create] do
    resource :join, only: [:create, :destroy]
  end
  
  resources :favours, only: [:create] do
    resources :bids, only: [:create]
    resource :completion, only: [:create]
  end
  
  post 'bids/:bid_id/accept' => 'accepts#create'
  

end

app/models/favour.rb
class Favour < ActiveRecord::Base
  
  include ErrorsHelper

  has_many :favour_clan_relationships
  has_many :clans, through: :favour_clan_relationships
  
  has_many :user_favour_relationships
  has_many :users_benefiting, through: :user_favour_relationships, source: :user
  
  has_many :bids
  
  def self.build_with(users_benefiting, clans, favour_params)
    Favour.new(favour_params).tap do |favour|
      favour.clans << clans
      favour.users_benefiting << users_benefiting
    end
  end
  
  def validate
    if(clans.empty? || description == '')
      set_error('You need to choose at least one clan') if clans.empty?
      set_error("Description can't be blank") if description == ''
      false
    else
      save
    end
  end
  
  def validate_completion(user)
    if users_benefiting.include?(user)
      save
    else
      set_error('You can only confirm completion of a favour if you benefit from the favour')
      false
    end
  end
  
end

app/controllers/concerns/favours_helper.rb
module FavoursHelper
  
  def generate_users_array(current_user,others_benefiting)
    users_array = [current_user]
    unless others_benefiting.nil?
      others_benefiting.each{|user_id| users_array << User.find(user_id.to_i)}
    end
    users_array
  end
  
  def generate_clans_array(clan_ids)
    clans_array = []
    unless clan_ids.nil?
      clan_ids.each_key{|clan_id| clans_array << Clan.find(clan_id.to_i)}
    end
    clans_array
  end
  
end

app/controllers/favours_controller.rb
class FavoursController < ApplicationController
  
  include FavoursHelper
  
  def create
    favour = Favour.build_with(users_benefiting, clans, favour_params)
    unless favour.validate
      flash[:errors] = favour.errors
    end
    redirect_to request.referer
  end
  
  private
  
  def clans
    generate_clans_array(params[:clan])
  end
  
  def users_benefiting
    generate_users_array(current_user,params[:users_benefiting])
  end
  
  def favour_params
    params.permit(:description)
  end
  
end

app/views/favours/formeindex.erb
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<div class='form-box'>
  <%= form_tag :favours do |f| %>
    <div id='help_first_step'>
      <h3>To post a new favour, first choose clans to post the favour in...</h3>
      <% @clans.each do |clan| %>
        <%= label_tag("clan[#{clan.id}]".to_sym, clan.name) %>
        <%= check_box_tag("clan[#{clan.id}]".to_sym) %>
      <% end %>
    </div>
    <div id='help_second_step'>
      <%= label_tag(:description, "Next, describe the favour...") %>
      <%= text_area_tag(:description, nil, rows: 5) %>
    </div>
    <div id='help_third_step' class='row'>
      <div class='col-md-6'>
        <h3>Choose anyone else this favour is for...</h3>
      </div>
      <div class='col-md-6'>
        <%= select_tag(:users_benefiting, options_from_collection_for_select(@users,:id,:username), {multiple: true}) %>
      </div>
    </div>
    <div id='help_fourth_step'>
      <%= submit_tag("Request help", class: 'help-button') %>
    </div>
  <% end %>
</div>

<% if @favours_for_me.count > 0 %>
  <div class='favours-benefiting-me summary'>
    <h1>Favours that'll help me...</h1>
    <ul><% @favours_for_me.each do |favour| %>
      <li class='row top-level'>
        <div class='col-md-3'>
          <%= favour.description %>
        </div>
        <div class='status col-md-3'>
          <%= favour.formeindex_status %>
        </div>
        <div class='col-md-6'>
          <% unless favour.bids.nil? %>
            <ul><% favour.bids.each do |bid| %>
              <li id='bid_<%=bid.id%>' class='row'>
                <div class='col-md-6'>
                  <%= "#{bid.user.username} bidded #{bid.amount}" %>
                </div>
                <div class='col-md-6'>
                  <% if favour.formeindex_status =~ /accepted/ %>
                    <% if bid.accepted %>
                      <%= button_to "#{bid.user.username} has done this favour", favour_completion_path(favour), class: 'favour-button' %>
                    <% end %>
                  <% elsif favour.formeindex_status =~ /carried/ %>
                    <% if bid.accepted %>
                      <%= bid.user.username %> did the favour
                    <% end %>
                  <% else %>
                    <%= button_to 'Accept bid', "bids/#{bid.id}/accept", class: 'favour-button' %>
                  <% end %>
                </div>
              </li>
            <% end %></ul>
          <% end %>
        </div>
      </li>
    <% end %></ul>
  </div>
<% end %>

app/views/favours/forothersindex.erb
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<% if @bid_on_favours.count > 0 %>
  <div class='favours-i-can-bid-on form-box'>
    <h1>Favours I can bid on...</h1>
    <ul><% @bid_on_favours.each do |favour| %>
      <li class='row'>
        <div class='col-md-4'>
          <%= favour.description %>
        </div>
        <div class='col-md-8'>
          <%= form_for [favour, @bid] do |f| %>
            <%= f.label :amount, "Number of thank you points" %>
            <%= f.number_field(:amount, in: 1.0..100.0) %>
            <%= f.submit "Bid", class: 'bid-button' %>
          <% end %>
        </div>
      </li>
    <% end %></ul>
  </div>
<% end %>

<% if @bidded_on_favours.count > 0 %>
  <div class='favours-i-bidded-on summary'>
    <h1>Favours I've bidded on...</h1>
    <ul><% @bidded_on_favours.each do |favour| %>
      <li class='row top-level'>
        <div class='col-md-6'>
          <%= favour.description %>
        </div>
        <div class='status col-md-6'>
          <%= favour.forothersindex_status(user: current_user) %>
        </div>
      </li>
    <% end %></ul>
  </div>
<% end %>