config/routes.rb
Rails.application.routes.draw do
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  root to: 'home#show', via: :get
  resource :dashboard, only: [:show]
  get 'favoursforothers' => 'favoursforothers#show'
  get 'favoursforme' => 'favoursforme#show'
  
  resources :clans, only: [:index, :create] do
    resource :join, only: [:create, :destroy]
  end
  
  resources :favours, only: [:create] do
    resources :bids, only: [:create]
    resource :completion, only: [:create]
  end
  
  post 'bids/:bid_id/accept' => 'accepts#create'
  

end

app/models/clan.rb
class Clan < ActiveRecord::Base
    
  has_many :user_clan_relationships
  has_many :users, through: :user_clan_relationships
  
  has_many :favour_clan_relationships
  has_many :favours, through: :favour_clan_relationships
  
  validates :name, presence: true, uniqueness: true
  
  def self.build_with(current_user, clan_params)
    self.new(clan_params).tap do |clan|
      clan.users << current_user
    end
  end
    
end

app/controllers/clans_controller.rb
class ClansController < ApplicationController
    
  def index
    @clansdisplay = ClansDisplay.new(current_user)
  end
  
  def create
    clan = Clan.build_with(current_user, clan_params)
    unless clan.save
      flash[:errors] = clan.errors.full_messages
    end
    redirect_to request.referer
  end
  
  private
  
  def clan_params
    params.require(:clan).permit(:name,:description)
  end
  
end

app/views/clans/_my_clan.erb
<li class='row top-level'>
  <div class='col-md-4'><%= clan.name %></div>
  <div class='col-md-4'><%= clan.description %></div>
  <div class='col-md-4'><%= button_to "Leave #{clan.name}", clan_join_path(clan), {method: :delete, class: 'full-width-black-button'} %></div>
</li>

app/views/clans/_my_clans.erb
<div class='myclans summary'>
  <h1>Clans I am in...</h1>
  <ul><% my_clans.each do |clan| %>
    <%= render partial: 'my_clan', locals: {clan: clan} %>
  <% end %></ul>
</div>

app/views/clans/_new_clan.erb
<div class='form-box'>
  <%= form_for new_clan do |f| %>
    <div id='clan_first_step'>
      <h3>To create a new clan, first give it a name...</h3>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div id='clan_second_step'>
      <%= f.label(:description, "Then describe the clan...") %>
      <%= f.text_area(:description, rows: 5) %>
    </div>
    <div id='clan_third_step'>
      <%= f.submit "Create new clan", class: 'full-width-transparent-button' %>
    </div>
  <% end %>
</div>

app/views/clans/_other_clan.erb
<li class='row top-level'>
  <div class='col-md-4'><%= clan.name %></div>
  <div class='col-md-4'><%= clan.description %></div>
  <div class='col-md-4'><%= button_to "Join #{clan.name}", clan_join_path(clan), class: 'full-width-black-button' %></div>
</li>

app/views/clans/_other_clans.erb
<div class='otherclans summary'>
  <h1>Clans I'm not in...</h1>
  <ul><% other_clans.each do |clan| %>
    <%= render partial: 'other_clan', locals: {clan: clan} %>
  <% end %></ul>
</div>

app/views/clans/index.erb
<%= render partial: 'new_clan', locals: {new_clan: @clansdisplay.new_clan} %>

<% if @clansdisplay.my_clans.count > 0 %>
  <%= render partial: 'my_clans', locals: {my_clans: @clansdisplay.my_clans} %>
<% end %>

<% if @clansdisplay.other_clans.count > 0 %>
  <%= render partial: 'other_clans', locals: {other_clans: @clansdisplay.other_clans} %>
<% end %>