config/routes.rb
Rails.application.routes.draw do
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  root to: 'home#show', via: :get
  resource :dashboard, only: [:show]
  get 'favoursforothers' => 'favoursforothers#show'
  get 'favoursforme' => 'favoursforme#show'
  
  resources :clans, only: [:index, :create] do
    resource :join, only: [:create, :destroy]
  end
  
  resources :favours, only: [:create] do
    resources :bids, only: [:create]
    resource :completion, only: [:create]
  end
  
  post 'bids/:bid_id/accept' => 'accepts#create'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :check_if_user_is_signed_in
    
  def show
  end
  
  private
  
  def check_if_user_is_signed_in
    if signed_in?
      redirect_to dashboard_path
    end
  end

end

app/views/home/show.erb
<div class='feature-box'>
  <h1>Welcome to Do Me A Favour,</h1>
  <h2>where your chores get done fairly and efficiently...</h2>
  <h2><%= link_to "Sign up", new_user_path %> to get started or <%= link_to "Sign in", new_session_path %> if you already have an account</h2>
</div>

app/views/home/signed_in.erb
<div class='feature-box'>
  <h1>Welcome to Do Me A Favour,</h1>
  <h2>where your chores get done fairly and efficiently...</h2>
</div>

<div class='row'>
  <div class='col-md-4'>
    <%= link_to "Manage my clans", clans_path, class: 'feature-button' %>
  </div>
  <div class='col-md-4'>
    <%= link_to "Favours for me", '/favoursforme', class: 'feature-button' %>
  </div>
  <div class='col-md-4'>
    <%= link_to "Favours for others", '/favoursforothers', class: 'feature-button' %>
  </div
</div>

app/views/home/signed_out.erb
<div class='feature-box'>
  <h1>Welcome to Do Me A Favour,</h1>
  <h2>where your chores get done fairly and efficiently...</h2>
  <h2><%= link_to "Sign up", new_user_path %> to get started or <%= link_to "Sign in", new_session_path %> if you already have an account</h2>
</div>