config/routes.rb
Rails.application.routes.draw do
  
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  root to: 'home#show', via: :get
  resource :dashboard, only: [:show]
  get 'favoursforothers' => 'favoursforothers#show'
  get 'favoursforme' => 'favoursforme#show'
  
  resources :clans, only: [:index, :create] do
    resource :join, only: [:create, :destroy]
  end
  
  resources :favours, only: [:create] do
    resources :bids, only: [:create]
    resource :completion, only: [:create]
  end
  
  post 'bids/:bid_id/accept' => 'accepts#create'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.erb
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

app/views/application/_navbar.erb
<nav class='navbar navbar-default navbar-fixed-top'>
  <div class='container'>
    <% if signed_in? %>
      <ul class='nav navbar-nav'>
        <li id='thankyoupoints'><%= current_user.thankyoupoints %> Thank You Points</li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to "#{current_user.username}'s dashboard", dashboard_path %></li>
        <li><%= link_to "Sign out", session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to "Sign in", new_session_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
      </ul>
    <% end %>
  </div>
</nav>